#!/bin/sh


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# MySQL
#
# If data dir exists, leave as is, otherwise create stuff.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/run_mysql.sh &

# TODO set up users and databases as expected by scripts

php-fpm

nginx -g "daemon off;"
